import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import PDFDocument from 'pdfkit';
import { ARCHETYPES } from '@/lib/data';
import { translations } from '@/lib/translations';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10' as any,
});

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const sessionId = searchParams.get('session_id');

  if (!sessionId) return new Response('Missing session', { status: 400 });

  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== 'paid') return new Response('Not paid', { status: 403 });

    const { archetype_id, lang, nickname } = session.metadata as any;
    const archetype = ARCHETYPES.find(a => a.id === archetype_id) || ARCHETYPES[0];
    const t = (translations as any)[lang || 'en'].result;

    // Create PDF
    const doc = new PDFDocument({ size: 'A4', margin: 0 });
    const chunks: any[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));

    // BACKGROUND
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#030303');

    // HEADER
    doc.fillColor('#00f2ff').font('Helvetica-Bold').fontSize(8).text('CLASSIFIED_DOSSIER // NEURAL_SCAN_UNIT_09', 40, 25);
    doc.fillColor('#ff4b2b').text('STATUS: TOP_SECRET', 450, 25);

    // TITLE
    doc.fillColor('#ffffff').fontSize(35).text('PLAYER', 40, 80).fillColor('#00f2ff').text('DNA', 205, 80);

    // SEAL (Simplified for node-pdfkit)
    doc.rect(400, 80, 150, 150).strokeColor('#00f2ff').stroke();
    doc.fillColor('#00f2ff').fontSize(10).text('VERIFIED_SEAL', 410, 100, { align: 'center', width: 130 });
    doc.fillColor('#ffffff').fontSize(6).text(`SUBJECT: ${nickname}`, 410, 180, { align: 'center', width: 130 });

    // CONTENT
    doc.fillColor('#00f2ff').fontSize(12).text('SUBJECT_IDENTITY', 40, 160);
    doc.fillColor('#ffffff').fontSize(20).text(lang === 'it' ? archetype.name_it : archetype.name, 40, 190);
    
    doc.fillColor('#888888').fontSize(10).text(lang === 'it' ? archetype.motivation_it : archetype.motivation, 40, 240, { width: 340 });

    // FOOTER
    doc.rect(0, 770, doc.page.width, 72).fill('#000000');
    doc.fillColor('#444444').fontSize(8).text('GENERATED BY PLAYERDNA NEURAL ENGINE', 0, 800, { align: 'center', width: doc.page.width });

    doc.end();

    const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });

    return new Response(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Cache-Control': 'no-cache',
      },
    });
  } catch (err: any) {
    console.error('PDF Generation Error:', err);
    return new Response(JSON.stringify({ error: err.message }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
