import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { ARCHETYPES } from '@/lib/data';
import { translations } from '@/lib/translations';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10' as any,
});

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const sessionId = searchParams.get('session_id');

  if (!sessionId) return new Response(JSON.stringify({ error: 'Missing session' }), { status: 400 });

  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== 'paid') return new Response(JSON.stringify({ error: 'Not paid' }), { status: 403 });

    const { archetype_id, lang, nickname } = session.metadata as any;
    const archetype = ARCHETYPES.find(a => a.id === archetype_id) || ARCHETYPES[0];
    
    // Create PDF
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]); // A4
    const { width, height } = page.getSize();
    
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);

    // BACKGROUND
    page.drawRectangle({
      x: 0,
      y: 0,
      width,
      height,
      color: rgb(0.01, 0.01, 0.01),
    });

    // HEADER BAR
    page.drawRectangle({
      x: 0,
      y: height - 60,
      width,
      height: 60,
      color: rgb(0, 0, 0),
    });

    page.drawText('CLASSIFIED_DOSSIER // NEURAL_SCAN_UNIT_09', {
      x: 40,
      y: height - 35,
      size: 8,
      font: fontBold,
      color: rgb(0, 0.95, 1),
    });

    page.drawText('STATUS: TOP_SECRET', {
      x: width - 150,
      y: height - 35,
      size: 8,
      font: fontBold,
      color: rgb(1, 0.29, 0.17),
    });

    // TITLE
    page.drawText('PLAYER', {
      x: 40,
      y: height - 120,
      size: 35,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText('DNA', {
      x: 205,
      y: height - 120,
      size: 35,
      font: fontBold,
      color: rgb(0, 0.95, 1),
    });

    // SEAL
    page.drawRectangle({
      x: 400,
      y: height - 230,
      width: 150,
      height: 150,
      borderColor: rgb(0, 0.95, 1),
      borderWidth: 1,
    });

    page.drawText('VERIFIED_SEAL', {
      x: 420,
      y: height - 110,
      size: 10,
      font: fontBold,
      color: rgb(0, 0.95, 1),
    });

    page.drawText(`SUBJECT: ${nickname || 'UNKNOWN'}`, {
      x: 410,
      y: height - 200,
      size: 7,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    // CONTENT
    page.drawText('SUBJECT_IDENTITY', {
      x: 40,
      y: height - 180,
      size: 12,
      font: fontBold,
      color: rgb(0, 0.95, 1),
    });

    const name = lang === 'it' ? archetype.name_it : archetype.name;
    page.drawText(name.toUpperCase(), {
      x: 40,
      y: height - 210,
      size: 20,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    const motivation = lang === 'it' ? archetype.motivation_it : archetype.motivation;
    const lines = wrapText(motivation, 50);
    let yPos = height - 250;
    lines.forEach(line => {
      page.drawText(line, {
        x: 40,
        y: yPos,
        size: 10,
        font: fontRegular,
        color: rgb(0.5, 0.5, 0.5),
      });
      yPos -= 14;
    });

    // FOOTER
    page.drawRectangle({
      x: 0,
      y: 0,
      width,
      height: 72,
      color: rgb(0, 0, 0),
    });

    page.drawText('GENERATED BY PLAYERDNA NEURAL ENGINE', {
      x: width / 2 - 100,
      y: 30,
      size: 8,
      font: fontRegular,
      color: rgb(0.26, 0.26, 0.26),
    });

    const pdfBytes = await pdfDoc.save();

    return new Response(pdfBytes as any, {
      headers: {
        'Content-Type': 'application/pdf',
        'Cache-Control': 'no-cache',
      },
    });
  } catch (err: any) {
    console.error('PDF Generation Error:', err);
    return new Response(JSON.stringify({ error: err.message }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  words.forEach(word => {
    if ((currentLine + word).length <= maxChars) {
      currentLine += word + ' ';
    } else {
      lines.push(currentLine.trim());
      currentLine = word + ' ';
    }
  });
  lines.push(currentLine.trim());
  return lines;
}
