"use client";
import { motion } from "framer-motion";
import { Archetype } from "@/lib/data";
import { Share2, Download, Trophy, Target, Zap, Shield, Brain, Fingerprint } from "lucide-react";
import { useRef } from "react";

interface ResultCardProps {
  archetype: Archetype;
}

export default function ResultCard({ archetype }: ResultCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);

  const traits = [
    { label: "EGO", value: archetype.traits.ego, icon: <Trophy className="w-3 h-3" /> },
    { label: "CLUTCH", value: archetype.traits.clutch, icon: <Target className="w-3 h-3" /> },
    { label: "TOXIC", value: archetype.traits.toxic, icon: <Zap className="w-3 h-3" /> },
    { label: "TACTICS", value: archetype.traits.tactics, icon: <Brain className="w-3 h-3" /> },
    { label: "RESILIENCE", value: archetype.traits.resilience, icon: <Shield className="w-3 h-3" /> },
  ];

  return (
    <motion.div
      ref={cardRef}
      initial={{ opacity: 0, y: 50, rotateY: 20 }}
      animate={{ opacity: 1, y: 0, rotateY: 0 }}
      className="relative w-full max-w-sm mx-auto glass-card rounded-[40px] p-10 overflow-hidden scanline shadow-[0_0_100px_rgba(0,0,0,1)]"
    >
      {/* Background Accent */}
      <div 
        className="absolute -top-40 -right-40 w-96 h-96 blur-[120px] opacity-30"
        style={{ backgroundColor: archetype.color }}
      />
      
      {/* Rarity Tag */}
      <div className="absolute top-8 left-8">
        <div className="px-3 py-1 border border-white/10 rounded-full bg-black/40 backdrop-blur-md">
          <span className="text-[9px] font-esports text-white/60 tracking-widest uppercase">
            Rarity: <span style={{ color: archetype.color }}>{archetype.rarity}%</span>
          </span>
        </div>
      </div>

      {/* Header */}
      <div className="text-center mt-12 mb-10">
        <h2 
          className="text-5xl font-esports italic font-black uppercase tracking-tighter leading-none mb-2"
          style={{ color: archetype.color, textShadow: `0 0 20px ${archetype.color}44` }}
        >
          {archetype.name}
        </h2>
        <span className="text-[10px] font-esports tracking-[0.4em] text-white/30 uppercase">
          Neural Match Confirmed
        </span>
      </div>

      {/* Central Visual */}
      <div className="relative h-56 flex items-center justify-center mb-10">
        <div className="absolute inset-0 flex items-center justify-center">
          <motion.div 
            animate={{ rotate: 360 }}
            transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
            className="w-48 h-48 rounded-full border border-white/5 border-dashed" 
          />
          <motion.div 
            animate={{ rotate: -360 }}
            transition={{ duration: 15, repeat: Infinity, ease: "linear" }}
            className="absolute w-56 h-56 rounded-full border border-white/5" 
          />
        </div>
        
        <div className="relative z-10 w-32 h-32 flex items-center justify-center bg-black/40 rounded-full border border-white/10 backdrop-blur-xl group">
          <Fingerprint className="w-16 h-16 text-white group-hover:scale-110 transition-transform duration-500" style={{ color: archetype.color }} />
        </div>
      </div>

      {/* Traits */}
      <div className="space-y-5 mb-12">
        {traits.map((trait) => (
          <div key={trait.label}>
            <div className="flex justify-between items-center text-[9px] font-esports text-white/40 mb-2 uppercase tracking-widest">
              <span className="flex items-center gap-2">{trait.icon} {trait.label}</span>
              <span style={{ color: archetype.color }}>{trait.value}%</span>
            </div>
            <div className="h-1 bg-white/5 rounded-full overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${trait.value}%` }}
                transition={{ duration: 1.5, ease: "easeOut" }}
                className="h-full"
                style={{ backgroundColor: archetype.color, boxShadow: `0 0 15px ${archetype.color}` }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Branding */}
      <div className="pt-8 border-t border-white/5 flex justify-between items-center">
        <div>
          <p className="text-[10px] font-esports text-white/20 uppercase tracking-widest mb-1">Generated by</p>
          <p className="text-xs font-esports font-black italic tracking-tighter">PLAYER<span className="text-dna-neon">DNA</span></p>
        </div>
        <div className="flex gap-3">
          <button className="p-3 bg-white/5 hover:bg-white/10 rounded-2xl transition-all border border-white/5">
            <Share2 className="w-5 h-5 text-white" />
          </button>
        </div>
      </div>
    </motion.div>
  );
}
